version: '2'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.4.14'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2.2.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  zeppelin:
    image: 'dylanmei/zeppelin:latest'
    ports:
      - '8080:8080'
